_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    WITH_IBN: True
  WEIGHTS: "fast-reid-uet/checkpoints/sbs_r50_ibn_best.pth"


DATASETS:
  NAMES: ("VTXReid",)
  TESTS: ("VTXReid",)

OUTPUT_DIR: logs/vtx_reid/sbs_R50-ibn
