_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    WITH_IBN: True
  WEIGHTS: "/home/ailab-rgb-1080ti/Work/uet-lab/VTX-MTMC/reid-model/fast-reid/pretrained_models/market_sbs_R50-ibn.pth"

DATASETS:
  NAMES: ("VTXReid",)
  TESTS: ("VTXReid",)

OUTPUT_DIR: logs/vtx_reid/sbs_R50-ibn
